R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
            //Unarmed
            "CUP_C_Datsun",
            "CUP_C_Datsun_4seat",
            "CUP_C_Datsun_Plain",
            "CUP_C_Datsun_Covered",
            "CUP_C_Datsun_Tubeframe",
            "CUP_C_Ural_Civ_01",
            "CUP_C_Ural_Civ_02",
            "CUP_C_Ural_Civ_03",
            "CUP_C_Ural_Open_Civ_01",
            "CUP_C_Ural_Open_Civ_02",
            "CUP_C_Ural_Open_Civ_03",
            "CUP_O_Ural_TKA",
            "CUP_O_Ural_RU",
            "CUP_I_Ural_UN",
            "CUP_B_Ural_CDF",
            "CUP_O_Ural_CHDKZ",
            "CUP_O_Ural_SLA",
            "CUP_O_Ural_Open_TKA",
            "CUP_B_Ural_Open_CDF",
            "CUP_O_Ural_Open_RU",
            "CUP_O_Ural_Open_CHDKZ",
            "CUP_O_Ural_Open_SLA",
            "CUP_O_Ural_Empty_SLA",
            "CUP_B_Ural_Empty_CDF",
            "CUP_I_Ural_Empty_UN",
            "CUP_O_Ural_Empty_RU",
            "CUP_O_Ural_Empty_CHDKZ",
            "CUP_O_Ural_Empty_TKA",
            "CUP_O_Ural_Repair_SLA",
            "CUP_O_Ural_Repair_TKA",
            "CUP_O_Ural_Repair_CHDKZ",
            "CUP_O_Ural_Repair_RU",
            "CUP_I_Ural_Repair_UN",
            "CUP_B_Ural_Repair_CDF",
            "CUP_B_Ural_Refuel_CDF",
            "CUP_O_Ural_Refuel_RU",
            "CUP_O_Ural_Refuel_CHDKZ",
            "CUP_O_Ural_Refuel_TKA",
            "CUP_O_Ural_Refuel_SLA",
            "CUP_C_LR_Transport_CTK",
            "CUP_O_LR_Transport_TKA",
            "CUP_O_LR_Transport_TKM",
            "CUP_B_LR_Transport_CZ_W",
            "CUP_B_LR_Transport_CZ_D",
            "CUP_B_LR_Transport_GB_W",
            "CUP_B_LR_Transport_GB_D",
            "CUP_B_LR_Ambulance_CZ_W",
            "CUP_B_LR_Ambulance_CZ_D",
            "CUP_B_LR_Ambulance_GB_W",
            "CUP_B_LR_Ambulance_GB_D",
            "CUP_O_LR_Ambulance_TKA",
            "CUP_C_UAZ_Unarmed_TK_CIV",
            "CUP_O_UAZ_Unarmed_RU",
            "CUP_I_UAZ_Unarmed_UN",
            "CUP_O_UAZ_Unarmed_TKA",
            "CUP_O_UAZ_Unarmed_CHDKZ",
            "CUP_B_UAZ_Unarmed_ACR",
            "CUP_B_UAZ_Unarmed_CDF",
            "CUP_C_UAZ_Open_TK_CIV",
            "CUP_O_UAZ_Open_CHDKZ",
            "CUP_O_UAZ_Open_RU",
            "CUP_O_UAZ_Open_TKA",
            "CUP_I_UAZ_Open_UN",
            "CUP_B_UAZ_Open_ACR",
            "CUP_B_UAZ_Open_CDF",
            "CUP_B_HMMWV_Unarmed_USA",
            "CUP_B_HMMWV_Unarmed_USMC",
            "CUP_B_HMMWV_Ambulance_USMC",
            "CUP_B_HMMWV_Ambulance_USA",
            "CUP_B_HMMWV_Ambulance_ACR",
            "CUP_B_HMMWV_Transport_USA",
            "CUP_I_M113_Med_RACS",
            "CUP_I_M113_Med_UN",
            
            //Armed
			"Wheeled_APC_F",
			"CUP_StrykerBase",
            "CUP_O_LR_MG_TKM",
            "CUP_O_LR_MG_TKA",
            "CUP_I_Datsun_PK",
            "CUP_I_Datsun_PK_Random",
            "CUP_I_Datsun_PK_TK",
            "CUP_I_Datsun_PK_TK_Random",
            "CUP_O_Datsun_PK",
            "CUP_O_Datsun_PK_Random",
            "CUP_O_UAZ_MG_CHDKZ",
            "CUP_O_UAZ_MG_RU",
            "CUP_O_UAZ_MG_TKA",
            "CUP_I_UAZ_MG_UN",
            "CUP_B_UAZ_MG_ACR",
            "CUP_B_UAZ_MG_CDF",
            "CUP_B_UAZ_AGS30_CDF",
            "CUP_O_UAZ_AGS30_CHDKZ",
            "CUP_O_UAZ_AGS30_RU",
            "CUP_O_UAZ_AGS30_TKA",
            "CUP_I_UAZ_AGS30_UN",
            "CUP_I_M113_RACS",
            "CUP_I_M113_UN",
            "CUP_BAF_Jackal2_L2A1_W",
            "CUP_BAF_Jackal2_L2A1_D",
            "CUP_BAF_Jackal2_GMG_D",
            "CUP_BAF_Jackal2_GMG_W",
            "CUP_B_LR_Special_CZ_W",
            "CUP_B_LR_Special_Des_CZ_D",
            "CUP_B_LR_MG_CZ_W",
            "CUP_B_LR_MG_GB_W",
            "CUP_B_HMMWV_M1114_USMC",
            "CUP_B_HMMWV_M2_USMC",
            "CUP_B_HMMWV_Crows_M2_USA",
            "CUP_B_HMMWV_M2_GPK_USA",
            "CUP_B_HMMWV_M2_USA",
            "CUP_B_HMMWV_DSHKM_GPK_ACR",
            "CUP_B_HMMWV_AGS_GPK_ACR",
            "CUP_B_HMMWV_MK19_USMC",
            "CUP_B_HMMWV_MK19_USA",
            "CUP_B_HMMWV_Crows_MK19_USA",
            "CUP_B_HMMWV_SOV_USA",
            "CUP_B_BRDM2_HQ_CDF",
            "CUP_O_BRDM2_HQ_SLA",
            "CUP_I_BRDM2_HQ_UN",
            "CUP_I_BRDM2_HQ_NAPA",
            "CUP_I_BRDM2_HQ_TK_Gue",
            "CUP_O_BRDM2_HQ_TKA",
            "CUP_O_BRDM2_HQ_CHDKZ",
            "CUP_O_BRDM2_CHDKZ",
            "CUP_O_BRDM2_SLA",
            "CUP_O_BRDM2_TKA",
            "CUP_I_BRDM2_NAPA",
            "CUP_I_BRDM2_TK_Gue",
            "CUP_I_BRDM2_UN",
            "CUP_B_BRDM2_CDF"
            
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
            //Unarmed
            "CUP_C_Datsun",
            "CUP_C_Datsun_4seat",
            "CUP_C_Datsun_Plain",
            "CUP_C_Datsun_Covered",
            "CUP_C_Datsun_Tubeframe",
            "CUP_C_Ural_Civ_01",
            "CUP_C_Ural_Civ_02",
            "CUP_C_Ural_Civ_03",
            "CUP_C_Ural_Open_Civ_01",
            "CUP_C_Ural_Open_Civ_02",
            "CUP_C_Ural_Open_Civ_03",
            "CUP_O_Ural_TKA",
            "CUP_O_Ural_RU",
            "CUP_I_Ural_UN",
            "CUP_B_Ural_CDF",
            "CUP_O_Ural_CHDKZ",
            "CUP_O_Ural_SLA",
            "CUP_O_Ural_Open_TKA",
            "CUP_B_Ural_Open_CDF",
            "CUP_O_Ural_Open_RU",
            "CUP_O_Ural_Open_CHDKZ",
            "CUP_O_Ural_Open_SLA",
            "CUP_O_Ural_Empty_SLA",
            "CUP_B_Ural_Empty_CDF",
            "CUP_I_Ural_Empty_UN",
            "CUP_O_Ural_Empty_RU",
            "CUP_O_Ural_Empty_CHDKZ",
            "CUP_O_Ural_Empty_TKA",
            "CUP_O_Ural_Repair_SLA",
            "CUP_O_Ural_Repair_TKA",
            "CUP_O_Ural_Repair_CHDKZ",
            "CUP_O_Ural_Repair_RU",
            "CUP_I_Ural_Repair_UN",
            "CUP_B_Ural_Repair_CDF",
            "CUP_B_Ural_Refuel_CDF",
            "CUP_O_Ural_Refuel_RU",
            "CUP_O_Ural_Refuel_CHDKZ",
            "CUP_O_Ural_Refuel_TKA",
            "CUP_O_Ural_Refuel_SLA",
            "CUP_C_LR_Transport_CTK",
            "CUP_O_LR_Transport_TKA",
            "CUP_O_LR_Transport_TKM",
            "CUP_B_LR_Transport_CZ_W",
            "CUP_B_LR_Transport_CZ_D",
            "CUP_B_LR_Transport_GB_W",
            "CUP_B_LR_Transport_GB_D",
            "CUP_B_LR_Ambulance_CZ_W",
            "CUP_B_LR_Ambulance_CZ_D",
            "CUP_B_LR_Ambulance_GB_W",
            "CUP_B_LR_Ambulance_GB_D",
            "CUP_O_LR_Ambulance_TKA",
            "CUP_C_UAZ_Unarmed_TK_CIV",
            "CUP_O_UAZ_Unarmed_RU",
            "CUP_I_UAZ_Unarmed_UN",
            "CUP_O_UAZ_Unarmed_TKA",
            "CUP_O_UAZ_Unarmed_CHDKZ",
            "CUP_B_UAZ_Unarmed_ACR",
            "CUP_B_UAZ_Unarmed_CDF",
            "CUP_C_UAZ_Open_TK_CIV",
            "CUP_O_UAZ_Open_CHDKZ",
            "CUP_O_UAZ_Open_RU",
            "CUP_O_UAZ_Open_TKA",
            "CUP_I_UAZ_Open_UN",
            "CUP_B_UAZ_Open_ACR",
            "CUP_B_UAZ_Open_CDF",
            "CUP_B_HMMWV_Unarmed_USA",
            "CUP_B_HMMWV_Unarmed_USMC",
            "CUP_B_HMMWV_Ambulance_USMC",
            "CUP_B_HMMWV_Ambulance_USA",
            "CUP_B_HMMWV_Ambulance_ACR",
            "CUP_B_HMMWV_Transport_USA",
            "CUP_I_M113_Med_RACS",
            "CUP_I_M113_Med_UN",
            
            //Armed
			"Wheeled_APC_F",
			"CUP_StrykerBase",
            "CUP_O_LR_MG_TKM",
            "CUP_O_LR_MG_TKA",
            "CUP_I_Datsun_PK",
            "CUP_I_Datsun_PK_Random",
            "CUP_I_Datsun_PK_TK",
            "CUP_I_Datsun_PK_TK_Random",
            "CUP_O_Datsun_PK",
            "CUP_O_Datsun_PK_Random",
            "CUP_O_UAZ_MG_CHDKZ",
            "CUP_O_UAZ_MG_RU",
            "CUP_O_UAZ_MG_TKA",
            "CUP_I_UAZ_MG_UN",
            "CUP_B_UAZ_MG_ACR",
            "CUP_B_UAZ_MG_CDF",
            "CUP_B_UAZ_AGS30_CDF",
            "CUP_O_UAZ_AGS30_CHDKZ",
            "CUP_O_UAZ_AGS30_RU",
            "CUP_O_UAZ_AGS30_TKA",
            "CUP_I_UAZ_AGS30_UN",
            "CUP_I_M113_RACS",
            "CUP_I_M113_UN",
            "CUP_BAF_Jackal2_L2A1_W",
            "CUP_BAF_Jackal2_L2A1_D",
            "CUP_BAF_Jackal2_GMG_D",
            "CUP_BAF_Jackal2_GMG_W",
            "CUP_B_LR_Special_CZ_W",
            "CUP_B_LR_Special_Des_CZ_D",
            "CUP_B_LR_MG_CZ_W",
            "CUP_B_LR_MG_GB_W",
            "CUP_B_HMMWV_M1114_USMC",
            "CUP_B_HMMWV_M2_USMC",
            "CUP_B_HMMWV_Crows_M2_USA",
            "CUP_B_HMMWV_M2_GPK_USA",
            "CUP_B_HMMWV_M2_USA",
            "CUP_B_HMMWV_DSHKM_GPK_ACR",
            "CUP_B_HMMWV_AGS_GPK_ACR",
            "CUP_B_HMMWV_MK19_USMC",
            "CUP_B_HMMWV_MK19_USA",
            "CUP_B_HMMWV_Crows_MK19_USA",
            "CUP_B_HMMWV_SOV_USA",
            "CUP_B_BRDM2_HQ_CDF",
            "CUP_O_BRDM2_HQ_SLA",
            "CUP_I_BRDM2_HQ_UN",
            "CUP_I_BRDM2_HQ_NAPA",
            "CUP_I_BRDM2_HQ_TK_Gue",
            "CUP_O_BRDM2_HQ_TKA",
            "CUP_O_BRDM2_HQ_CHDKZ",
            "CUP_O_BRDM2_CHDKZ",
            "CUP_O_BRDM2_SLA",
            "CUP_O_BRDM2_TKA",
            "CUP_I_BRDM2_NAPA",
            "CUP_I_BRDM2_TK_Gue",
            "CUP_I_BRDM2_UN",
            "CUP_B_BRDM2_CDF"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
            //Unarmed
            "CUP_C_Datsun",
            "CUP_C_Datsun_4seat",
            "CUP_C_Datsun_Plain",
            "CUP_C_Datsun_Covered",
            "CUP_C_Datsun_Tubeframe",
            "CUP_C_Ural_Civ_01",
            "CUP_C_Ural_Civ_02",
            "CUP_C_Ural_Civ_03",
            "CUP_C_Ural_Open_Civ_01",
            "CUP_C_Ural_Open_Civ_02",
            "CUP_C_Ural_Open_Civ_03",
            "CUP_O_Ural_TKA",
            "CUP_O_Ural_RU",
            "CUP_I_Ural_UN",
            "CUP_B_Ural_CDF",
            "CUP_O_Ural_CHDKZ",
            "CUP_O_Ural_SLA",
            "CUP_O_Ural_Open_TKA",
            "CUP_B_Ural_Open_CDF",
            "CUP_O_Ural_Open_RU",
            "CUP_O_Ural_Open_CHDKZ",
            "CUP_O_Ural_Open_SLA",
            "CUP_O_Ural_Empty_SLA",
            "CUP_B_Ural_Empty_CDF",
            "CUP_I_Ural_Empty_UN",
            "CUP_O_Ural_Empty_RU",
            "CUP_O_Ural_Empty_CHDKZ",
            "CUP_O_Ural_Empty_TKA",
            "CUP_O_Ural_Repair_SLA",
            "CUP_O_Ural_Repair_TKA",
            "CUP_O_Ural_Repair_CHDKZ",
            "CUP_O_Ural_Repair_RU",
            "CUP_I_Ural_Repair_UN",
            "CUP_B_Ural_Repair_CDF",
            "CUP_B_Ural_Refuel_CDF",
            "CUP_O_Ural_Refuel_RU",
            "CUP_O_Ural_Refuel_CHDKZ",
            "CUP_O_Ural_Refuel_TKA",
            "CUP_O_Ural_Refuel_SLA",
            "CUP_C_LR_Transport_CTK",
            "CUP_O_LR_Transport_TKA",
            "CUP_O_LR_Transport_TKM",
            "CUP_B_LR_Transport_CZ_W",
            "CUP_B_LR_Transport_CZ_D",
            "CUP_B_LR_Transport_GB_W",
            "CUP_B_LR_Transport_GB_D",
            "CUP_B_LR_Ambulance_CZ_W",
            "CUP_B_LR_Ambulance_CZ_D",
            "CUP_B_LR_Ambulance_GB_W",
            "CUP_B_LR_Ambulance_GB_D",
            "CUP_O_LR_Ambulance_TKA",
            "CUP_C_UAZ_Unarmed_TK_CIV",
            "CUP_O_UAZ_Unarmed_RU",
            "CUP_I_UAZ_Unarmed_UN",
            "CUP_O_UAZ_Unarmed_TKA",
            "CUP_O_UAZ_Unarmed_CHDKZ",
            "CUP_B_UAZ_Unarmed_ACR",
            "CUP_B_UAZ_Unarmed_CDF",
            "CUP_C_UAZ_Open_TK_CIV",
            "CUP_O_UAZ_Open_CHDKZ",
            "CUP_O_UAZ_Open_RU",
            "CUP_O_UAZ_Open_TKA",
            "CUP_I_UAZ_Open_UN",
            "CUP_B_UAZ_Open_ACR",
            "CUP_B_UAZ_Open_CDF",
            "CUP_B_HMMWV_Unarmed_USA",
            "CUP_B_HMMWV_Unarmed_USMC",
            "CUP_B_HMMWV_Ambulance_USMC",
            "CUP_B_HMMWV_Ambulance_USA",
            "CUP_B_HMMWV_Ambulance_ACR",
            "CUP_B_HMMWV_Transport_USA",
            "CUP_I_M113_Med_RACS",
            "CUP_I_M113_Med_UN",
            
            //Armed
			"Wheeled_APC_F",
			"CUP_StrykerBase",
            "CUP_O_LR_MG_TKM",
            "CUP_O_LR_MG_TKA",
            "CUP_I_Datsun_PK",
            "CUP_I_Datsun_PK_Random",
            "CUP_I_Datsun_PK_TK",
            "CUP_I_Datsun_PK_TK_Random",
            "CUP_O_Datsun_PK",
            "CUP_O_Datsun_PK_Random",
            "CUP_O_UAZ_MG_CHDKZ",
            "CUP_O_UAZ_MG_RU",
            "CUP_O_UAZ_MG_TKA",
            "CUP_I_UAZ_MG_UN",
            "CUP_B_UAZ_MG_ACR",
            "CUP_B_UAZ_MG_CDF",
            "CUP_B_UAZ_AGS30_CDF",
            "CUP_O_UAZ_AGS30_CHDKZ",
            "CUP_O_UAZ_AGS30_RU",
            "CUP_O_UAZ_AGS30_TKA",
            "CUP_I_UAZ_AGS30_UN",
            "CUP_I_M113_RACS",
            "CUP_I_M113_UN",
            "CUP_BAF_Jackal2_L2A1_W",
            "CUP_BAF_Jackal2_L2A1_D",
            "CUP_BAF_Jackal2_GMG_D",
            "CUP_BAF_Jackal2_GMG_W",
            "CUP_B_LR_Special_CZ_W",
            "CUP_B_LR_Special_Des_CZ_D",
            "CUP_B_LR_MG_CZ_W",
            "CUP_B_LR_MG_GB_W",
            "CUP_B_HMMWV_M1114_USMC",
            "CUP_B_HMMWV_M2_USMC",
            "CUP_B_HMMWV_Crows_M2_USA",
            "CUP_B_HMMWV_M2_GPK_USA",
            "CUP_B_HMMWV_M2_USA",
            "CUP_B_HMMWV_DSHKM_GPK_ACR",
            "CUP_B_HMMWV_AGS_GPK_ACR",
            "CUP_B_HMMWV_MK19_USMC",
            "CUP_B_HMMWV_MK19_USA",
            "CUP_B_HMMWV_Crows_MK19_USA",
            "CUP_B_HMMWV_SOV_USA",
            "CUP_B_BRDM2_HQ_CDF",
            "CUP_O_BRDM2_HQ_SLA",
            "CUP_I_BRDM2_HQ_UN",
            "CUP_I_BRDM2_HQ_NAPA",
            "CUP_I_BRDM2_HQ_TK_Gue",
            "CUP_O_BRDM2_HQ_TKA",
            "CUP_O_BRDM2_HQ_CHDKZ",
            "CUP_O_BRDM2_CHDKZ",
            "CUP_O_BRDM2_SLA",
            "CUP_O_BRDM2_TKA",
            "CUP_I_BRDM2_NAPA",
            "CUP_I_BRDM2_TK_Gue",
            "CUP_I_BRDM2_UN",
            "CUP_B_BRDM2_CDF"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
            //Unarmed			
            ["CUP_C_Datsun", 25],
            ["CUP_C_Datsun_4seat", 25],
            ["CUP_C_Datsun_Plain", 25],
            ["CUP_C_Datsun_Covered", 25],
            ["CUP_C_Datsun_Tubeframe", 25],
            ["CUP_C_Ural_Civ_01", 25],
            ["CUP_C_Ural_Civ_02", 25],
            ["CUP_C_Ural_Civ_03", 25],
            ["CUP_C_Ural_Open_Civ_01", 25],
            ["CUP_C_Ural_Open_Civ_02", 25],
            ["CUP_C_Ural_Open_Civ_03", 25],
            ["CUP_O_Ural_TKA", 25],
            ["CUP_O_Ural_RU", 25],
            ["CUP_I_Ural_UN", 25],
            ["CUP_B_Ural_CDF", 25],
            ["CUP_O_Ural_CHDKZ", 25],
            ["CUP_O_Ural_SLA", 25],
            ["CUP_O_Ural_Open_TKA", 25],
            ["CUP_B_Ural_Open_CDF", 25],
            ["CUP_O_Ural_Open_RU", 25],
            ["CUP_O_Ural_Open_CHDKZ", 25],
            ["CUP_O_Ural_Open_SLA", 25],
            ["CUP_O_Ural_Empty_SLA", 25],
            ["CUP_B_Ural_Empty_CDF", 25],
            ["CUP_I_Ural_Empty_UN", 25],
            ["CUP_O_Ural_Empty_RU", 25],
            ["CUP_O_Ural_Empty_CHDKZ", 25],
            ["CUP_O_Ural_Empty_TKA", 25],
            ["CUP_O_Ural_Repair_SLA", 25],
            ["CUP_O_Ural_Repair_TKA", 25],
            ["CUP_O_Ural_Repair_CHDKZ", 25],
            ["CUP_O_Ural_Repair_RU", 25],
            ["CUP_I_Ural_Repair_UN", 25],
            ["CUP_B_Ural_Repair_CDF", 25],
            ["CUP_B_Ural_Refuel_CDF", 25],
            ["CUP_O_Ural_Refuel_RU", 25],
            ["CUP_O_Ural_Refuel_CHDKZ", 25],
            ["CUP_O_Ural_Refuel_TKA", 25],
            ["CUP_O_Ural_Refuel_SLA", 25],
            ["CUP_C_LR_Transport_CTK", 50],
            ["CUP_O_LR_Transport_TKA", 50],
            ["CUP_O_LR_Transport_TKM", 50],
            ["CUP_B_LR_Transport_CZ_W", 50],
            ["CUP_B_LR_Transport_CZ_D", 50],
            ["CUP_B_LR_Transport_GB_W", 50],
            ["CUP_B_LR_Transport_GB_D", 50],
            ["CUP_B_LR_Ambulance_CZ_W", 25],
            ["CUP_B_LR_Ambulance_CZ_D", 25],
            ["CUP_B_LR_Ambulance_GB_W", 25],
            ["CUP_B_LR_Ambulance_GB_D", 25],
            ["CUP_O_LR_Ambulance_TKA", 25],
            ["CUP_C_UAZ_Unarmed_TK_CIV", 25],
            ["CUP_O_UAZ_Unarmed_RU", 25],
            ["CUP_I_UAZ_Unarmed_UN", 25],
            ["CUP_O_UAZ_Unarmed_TKA", 25],
            ["CUP_O_UAZ_Unarmed_CHDKZ", 25],
            ["CUP_B_UAZ_Unarmed_ACR", 25],
            ["CUP_B_UAZ_Unarmed_CDF", 25],
            ["CUP_C_UAZ_Open_TK_CIV", 25],
            ["CUP_O_UAZ_Open_CHDKZ", 25],
            ["CUP_O_UAZ_Open_RU", 25],
            ["CUP_O_UAZ_Open_TKA", 25],
            ["CUP_I_UAZ_Open_UN", 25],
            ["CUP_B_UAZ_Open_ACR", 25],
            ["CUP_B_UAZ_Open_CDF", 25],
            ["CUP_B_HMMWV_Unarmed_USA", 25],
            ["CUP_B_HMMWV_Unarmed_USMC", 25],
            ["CUP_B_HMMWV_Ambulance_USMC", 25],
            ["CUP_B_HMMWV_Ambulance_USA", 25],
            ["CUP_B_HMMWV_Ambulance_ACR", 25],
            ["CUP_B_HMMWV_Transport_USA", 50],
            ["CUP_I_M113_Med_RACS", 25],
            ["CUP_I_M113_Med_UN", 25],
            
            //Armed
			["Wheeled_APC_F",50],
			["CUP_StrykerBase", 50],
            ["CUP_O_LR_MG_TKM", 25],
            ["CUP_O_LR_MG_TKA", 25],
            ["CUP_I_Datsun_PK", 25],
            ["CUP_I_Datsun_PK_Random", 25],
            ["CUP_I_Datsun_PK_TK", 25],
            ["CUP_I_Datsun_PK_TK_Random", 25],
            ["CUP_O_Datsun_PK", 25],
            ["CUP_O_Datsun_PK_Random", 25],
            ["CUP_O_UAZ_MG_CHDKZ", 25],
            ["CUP_O_UAZ_MG_RU", 25],
            ["CUP_O_UAZ_MG_TKA", 25],
            ["CUP_I_UAZ_MG_UN", 25],
            ["CUP_B_UAZ_MG_ACR", 25],
            ["CUP_B_UAZ_MG_CDF", 25],
            ["CUP_B_UAZ_AGS30_CDF", 25],
            ["CUP_O_UAZ_AGS30_CHDKZ", 25],
            ["CUP_O_UAZ_AGS30_RU", 25],
            ["CUP_O_UAZ_AGS30_TKA", 25],
            ["CUP_I_UAZ_AGS30_UN", 25],
            ["CUP_I_M113_RACS", 25],
            ["CUP_I_M113_UN", 25],
            ["CUP_BAF_Jackal2_L2A1_W", 25],
            ["CUP_BAF_Jackal2_L2A1_D", 25],
            ["CUP_BAF_Jackal2_GMG_D", 25],
            ["CUP_BAF_Jackal2_GMG_W", 25],
            ["CUP_B_LR_Special_CZ_W", 25],
            ["CUP_B_LR_Special_Des_CZ_D", 25],
            ["CUP_B_LR_MG_CZ_W", 25],
            ["CUP_B_LR_MG_GB_W", 25],
            ["CUP_B_HMMWV_M1114_USMC", 25],
            ["CUP_B_HMMWV_M2_USMC", 25],
            ["CUP_B_HMMWV_Crows_M2_USA", 25],
            ["CUP_B_HMMWV_M2_GPK_USA", 25],
            ["CUP_B_HMMWV_M2_USA", 25],
            ["CUP_B_HMMWV_DSHKM_GPK_ACR", 25],
            ["CUP_B_HMMWV_AGS_GPK_ACR", 25],
            ["CUP_B_HMMWV_MK19_USMC", 25],
            ["CUP_B_HMMWV_MK19_USA", 25],
            ["CUP_B_HMMWV_Crows_MK19_USA", 25],
            ["CUP_B_HMMWV_SOV_USA", 25],
            ["CUP_B_BRDM2_HQ_CDF", 25],
            ["CUP_O_BRDM2_HQ_SLA", 25],
            ["CUP_I_BRDM2_HQ_UN", 25],
            ["CUP_I_BRDM2_HQ_NAPA", 25],
            ["CUP_I_BRDM2_HQ_TK_Gue", 25],
            ["CUP_O_BRDM2_HQ_TKA", 25],
            ["CUP_O_BRDM2_HQ_CHDKZ", 25],
            ["CUP_O_BRDM2_CHDKZ", 25],
            ["CUP_O_BRDM2_SLA", 25],
            ["CUP_O_BRDM2_TKA", 25],
            ["CUP_I_BRDM2_NAPA", 25],
            ["CUP_I_BRDM2_TK_Gue", 25],
            ["CUP_I_BRDM2_UN", 25],
            ["CUP_B_BRDM2_CDF", 25]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
    
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
    
];