R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
            //Trucks
            "B_Truck_01_transport_F",
            "B_Truck_01_covered_F",
            "B_Truck_01_mover_F",
            "B_Truck_01_box_F",
            "B_Truck_01_Repair_F", 
            "B_Truck_01_ammo_F",
            "B_Truck_01_fuel_F",
            "B_Truck_01_medical_F", 
            "B_G_Van_01_transport_F", 
            "B_G_Van_01_fuel_F",
            "O_G_Offroad_01_repair_F", 
            "O_G_Offroad_01_F",
            "O_Truck_02_covered_F",
            "O_Truck_02_transport_F", 
            "O_Truck_03_transport_F",
            "O_Truck_03_covered_F",
            "O_Truck_03_repair_F",
            "O_Truck_03_ammo_F",
            "O_Truck_03_fuel_F",
            "O_Truck_03_medical_F", 
            "O_Truck_03_device_F",
            "O_Truck_02_box_F",
            "O_Truck_02_medical_F", 
            "O_Truck_02_Ammo_F",
            "O_Truck_02_fuel_F",
            "O_G_Van_01_transport_F",
            "O_G_Van_01_fuel_F",
            "I_G_Offroad_01_F",
            "I_G_Offroad_01_armed_F", 
            "I_Truck_02_transport_F",
            "I_Truck_02_ammo_F",
            "I_Truck_02_box_F",
            "I_Truck_02_medical_F", 
            "I_Truck_02_fuel_F",
            "I_G_Van_01_transport_F", 
            "I_G_Van_01_fuel_F",
                       
            //Armed
            "B_G_Offroad_01_armed_F", 
            "O_G_Offroad_01_armed_F",
            "B_MRAP_01_gmg_F", 
            "B_MRAP_01_hmg_F",
            "O_MRAP_02_gmg_F",  
            "O_MRAP_02_hmg_F",
            "I_MRAP_03_hmg_F", 
            "I_MRAP_03_gmg_F",
            "B_APC_Wheeled_01_cannon_F",            
            "I_APC_Wheeled_03_cannon_F",
            
            //Tanks
            "B_APC_Tracked_01_rcws_F",
            "B_APC_Tracked_01_CRV_F",
            "B_APC_Tracked_01_AA_F",
            "B_MBT_01_arty_F",
            "B_MBT_01_mlrs_F",
            "B_MBT_01_TUSK_F",
            "O_APC_Tracked_02_cannon_F", 
            "O_APC_Tracked_02_AA_F",
            "O_MBT_02_cannon_F",
            "O_MBT_02_arty_F",
            "O_APC_Wheeled_02_rcws_F", 
            "I_APC_tracked_03_cannon_F",
            "I_MBT_03_cannon_F"           
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
            //Cars
            "B_G_Offroad_01_F",
            "B_G_Offroad_01_repair_F", 
            "B_G_Quadbike_01_F",
            "B_MRAP_01_F",
            "B_Quadbike_01_F",
            "O_G_Quadbike_01_F", 
            "O_MRAP_02_F",
            "O_Quadbike_01_F",
            "I_Quadbike_01_F",
            "I_G_Quadbike_01_F", 
            "I_MRAP_03_F",
            "C_Offroad_02_unarmed_F",
            "C_Offroad_02_unarmed_black_F",
            "C_Offroad_02_unarmed_blue_F",
            "C_Offroad_02_unarmed_green_F",
            "C_Offroad_02_unarmed_orange_F",
            "C_Offroad_02_unarmed_red_F",
            "C_Offroad_02_unarmed_white_F",
            "I_C_Offroad_02_unarmed_F",
            "I_C_Offroad_02_unarmed_brown_F",
            "I_C_Offroad_02_unarmed_olive_F",
            "B_T_MRAP_01_F",
            "B_T_LSV_01_armed_F",                        
            "B_T_LSV_01_armed_CTRG_F",                 
            "B_T_LSV_01_unarmed_F",                      
            "B_T_LSV_01_unarmed_CTRG_F",                
            "B_LSV_01_armed_F",                          
            "B_LSV_01_unarmed_F",                        
            "B_CTRG_LSV_01_light_F",                     
            "B_LSV_01_armed_black_F",                    
            "B_LSV_01_armed_olive_F",                    
            "B_LSV_01_armed_sand_F",                     
            "B_LSV_01_unarmed_black_F",                  
            "B_LSV_01_unarmed_olive_F",                  
            "B_LSV_01_unarmed_sand_F",                   
            "B_T_LSV_01_armed_black_F",                  
            "B_T_LSV_01_armed_olive_F",                  
            "B_T_LSV_01_armed_sand_F",                   
            "B_T_LSV_01_unarmed_black_F",                
            "B_T_LSV_01_unarmed_olive_F",                
            "B_T_LSV_01_unarmed_sand_F",
            "O_T_LSV_02_armed_F",     
            "O_T_LSV_02_armed_viper_F",                  
            "O_T_LSV_02_unarmed_F",     
            "O_T_LSV_02_unarmed_viper_F",
            "O_LSV_02_armed_F",       
            "O_LSV_02_armed_viper_F", 
            "O_LSV_02_unarmed_F",       
            "O_LSV_02_unarmed_viper_F", 
            "O_T_LSV_02_armed_black_F",                  
            "O_T_LSV_02_armed_ghex_F",
            "O_T_LSV_02_armed_arid_F",
            "O_T_LSV_02_unarmed_black_F",
            "O_T_LSV_02_unarmed_ghex_F",
            "O_T_LSV_02_unarmed_arid_F",
            "O_LSV_02_armed_black_F", 
            "O_LSV_02_armed_ghex_F",  
            "O_LSV_02_armed_arid_F",
            "O_LSV_02_unarmed_black_F", 
            "O_LSV_02_unarmed_ghex_F",  
            "O_LSV_02_unarmed_arid_F",
            "O_T_Quadbike_01_ghex_F",
                        
            //Trucks
            "B_Truck_01_transport_F",
            "B_Truck_01_covered_F",
            "B_Truck_01_mover_F",
            "B_Truck_01_box_F",
            "B_Truck_01_Repair_F", 
            "B_Truck_01_ammo_F",
            "B_Truck_01_fuel_F",
            "B_Truck_01_medical_F", 
            "B_G_Van_01_transport_F", 
            "B_G_Van_01_fuel_F",
            "O_G_Offroad_01_repair_F", 
            "O_G_Offroad_01_F",
            "O_Truck_02_covered_F",
            "O_Truck_02_transport_F", 
            "O_Truck_03_transport_F",
            "O_Truck_03_covered_F",
            "O_Truck_03_repair_F",
            "O_Truck_03_ammo_F",
            "O_Truck_03_fuel_F",
            "O_Truck_03_medical_F", 
            "O_Truck_03_device_F",
            "O_Truck_02_box_F",
            "O_Truck_02_medical_F", 
            "O_Truck_02_Ammo_F",
            "O_Truck_02_fuel_F",
            "O_G_Van_01_transport_F",
            "O_G_Van_01_fuel_F",
            "I_G_Offroad_01_F",
            "I_G_Offroad_01_armed_F", 
            "I_Truck_02_transport_F",
            "I_Truck_02_ammo_F",
            "I_Truck_02_box_F",
            "I_Truck_02_medical_F", 
            "I_Truck_02_fuel_F",
            "I_G_Van_01_transport_F", 
            "I_G_Van_01_fuel_F",
            "B_T_Truck_01_mover_F",
            "B_T_Truck_01_transport_F",
            "B_T_Truck_01_covered_F",
            "O_T_Truck_03_transport_ghex_F",
            "O_T_Truck_03_covered_ghex_F",
            "O_T_Truck_03_device_ghex_F",
            "I_C_Van_01_transport_F",
            "I_C_Van_01_transport_brown_F",
            "I_C_Van_01_transport_olive_F",
            
            //Armed
            "B_G_Offroad_01_armed_F", 
            "O_G_Offroad_01_armed_F",
            "B_MRAP_01_gmg_F", 
            "B_MRAP_01_hmg_F",
            "O_MRAP_02_gmg_F",  
            "O_MRAP_02_hmg_F",
            "I_MRAP_03_hmg_F", 
            "I_MRAP_03_gmg_F",
            "B_APC_Wheeled_01_cannon_F",            
            "I_APC_Wheeled_03_cannon_F",
            
            //Tanks
            "B_APC_Tracked_01_rcws_F",
            "B_APC_Tracked_01_CRV_F",
            "B_APC_Tracked_01_AA_F",
            "B_MBT_01_arty_F",
            "B_MBT_01_mlrs_F",
            "B_MBT_01_TUSK_F",
            "O_APC_Tracked_02_cannon_F", 
            "O_APC_Tracked_02_AA_F",
            "O_MBT_02_cannon_F",
            "O_MBT_02_arty_F",
            "O_APC_Wheeled_02_rcws_F", 
            "I_APC_tracked_03_cannon_F",
            "I_MBT_03_cannon_F"
                      
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
                 
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
            //Cars
            ["B_G_Offroad_01_F", 20],
            ["B_G_Offroad_01_repair_F", 20],
            ["B_G_Quadbike_01_F", 10],
            ["B_MRAP_01_F", 25],
            ["B_Quadbike_01_F", 10],
            ["O_G_Quadbike_01_F", 10], 
            ["O_MRAP_02_F", 25],
            ["O_Quadbike_01_F", 10],
            ["I_Quadbike_01_F", 10],
            ["I_G_Quadbike_01_F", 10],
            ["I_MRAP_03_F", 25],
            ["C_Offroad_02_unarmed_F", 20],
            ["C_Offroad_02_unarmed_black_F", 20],
            ["C_Offroad_02_unarmed_blue_F", 20],
            ["C_Offroad_02_unarmed_green_F", 20],
            ["C_Offroad_02_unarmed_orange_F", 20],
            ["C_Offroad_02_unarmed_red_F", 20],
            ["C_Offroad_02_unarmed_white_F", 20],
            ["I_C_Offroad_02_unarmed_F", 20],
            ["I_C_Offroad_02_unarmed_brown_F", 20],
            ["I_C_Offroad_02_unarmed_olive_F", 20],
            ["B_T_MRAP_01_F", 25],
            ["B_T_LSV_01_armed_F", 25],                        
            ["B_T_LSV_01_armed_CTRG_F", 25],                 
            ["B_T_LSV_01_unarmed_F", 25],                      
            ["B_T_LSV_01_unarmed_CTRG_F", 25],                
            ["B_LSV_01_armed_F", 25],                          
            ["B_LSV_01_unarmed_F", 25],                        
            ["B_CTRG_LSV_01_light_F", 25],                     
            ["B_LSV_01_armed_black_F", 25],                   
            ["B_LSV_01_armed_olive_F", 25],                    
            ["B_LSV_01_armed_sand_F", 25],                    
            ["B_LSV_01_unarmed_black_F", 25],                  
            ["B_LSV_01_unarmed_olive_F", 25],                  
            ["B_LSV_01_unarmed_sand_F", 25],                   
            ["B_T_LSV_01_armed_black_F", 25],                  
            ["B_T_LSV_01_armed_olive_F", 25],                  
            ["B_T_LSV_01_armed_sand_F", 25],                  
            ["B_T_LSV_01_unarmed_black_F", 25],                
            ["B_T_LSV_01_unarmed_olive_F", 25],                
            ["B_T_LSV_01_unarmed_sand_F", 25],
            ["O_T_LSV_02_armed_F", 25],     
            ["O_T_LSV_02_armed_viper_F", 25],                  
            ["O_T_LSV_02_unarmed_F", 25],     
            ["O_T_LSV_02_unarmed_viper_F", 25],
            ["O_LSV_02_armed_F", 25],       
            ["O_LSV_02_armed_viper_F", 25], 
            ["O_LSV_02_unarmed_F", 25],       
            ["O_LSV_02_unarmed_viper_F", 25], 
            ["O_T_LSV_02_armed_black_F", 25],                  
            ["O_T_LSV_02_armed_ghex_F", 25],
            ["O_T_LSV_02_armed_arid_F", 25],
            ["O_T_LSV_02_unarmed_black_F", 25],
            ["O_T_LSV_02_unarmed_ghex_F", 25],
            ["O_T_LSV_02_unarmed_arid_F", 25],
            ["O_LSV_02_armed_black_F", 25], 
            ["O_LSV_02_armed_ghex_F", 25],  
            ["O_LSV_02_armed_arid_F", 25],
            ["O_LSV_02_unarmed_black_F", 25], 
            ["O_LSV_02_unarmed_ghex_F", 25],  
            ["O_LSV_02_unarmed_arid_F", 25],
            ["O_T_Quadbike_01_ghex_F", 10],
                        
            //Trucks
            ["B_Truck_01_transport_F", 100],
            ["B_Truck_01_covered_F", 100],
            ["B_Truck_01_mover_F", 100],
            ["B_Truck_01_box_F", 100],
            ["B_Truck_01_Repair_F", 25],
            ["B_Truck_01_ammo_F", 50],
            ["B_Truck_01_fuel_F", 25],
            ["B_Truck_01_medical_F", 25], 
            ["B_G_Van_01_transport_F", 50], 
            ["B_G_Van_01_fuel_F", 25],
            ["O_G_Offroad_01_repair_F", 25], 
            ["O_G_Offroad_01_F", 25],
            ["O_Truck_02_covered_F", 50],
            ["O_Truck_02_transport_F", 100],
            ["O_Truck_03_transport_F", 100],
            ["O_Truck_03_covered_F", 100],
            ["O_Truck_03_repair_F", 25],
            ["O_Truck_03_ammo_F", 50],
            ["O_Truck_03_fuel_F", 25],
            ["O_Truck_03_medical_F", 25],
            ["O_Truck_03_device_F", 25],
            ["O_Truck_02_box_F", 100],
            ["O_Truck_02_medical_F", 25], 
            ["O_Truck_02_Ammo_F", 50],
            ["O_Truck_02_fuel_F", 25],
            ["O_G_Van_01_transport_F", 50],
            ["O_G_Van_01_fuel_F", 25],
            ["I_G_Offroad_01_F", 25],
            ["I_G_Offroad_01_armed_F", 25], 
            ["I_Truck_02_transport_F", 100],
            ["I_Truck_02_ammo_F", 50],
            ["I_Truck_02_box_F", 25],
            ["I_Truck_02_medical_F", 25], 
            ["I_Truck_02_fuel_F", 25],
            ["I_G_Van_01_transport_F", 50], 
            ["I_G_Van_01_fuel_F", 25],
            ["B_T_Truck_01_mover_F", 100],
            ["B_T_Truck_01_transport_F", 100],
            ["B_T_Truck_01_covered_F", 100],
            ["O_T_Truck_03_transport_ghex_F", 100],
            ["O_T_Truck_03_covered_ghex_F", 100],
            ["O_T_Truck_03_device_ghex_F", 100],
            ["I_C_Van_01_transport_F", 100],
            ["I_C_Van_01_transport_brown_F", 100],
            ["I_C_Van_01_transport_olive_F", 100],
            
            //Armed
            ["B_G_Offroad_01_armed_F", 25],
            ["O_G_Offroad_01_armed_F", 25],
            ["B_MRAP_01_gmg_F", 50],
            ["B_MRAP_01_hmg_F", 50],
            ["O_MRAP_02_gmg_F", 50],  
            ["O_MRAP_02_hmg_F", 50],
            ["I_MRAP_03_hmg_F", 50], 
            ["I_MRAP_03_gmg_F", 50],
            ["B_APC_Wheeled_01_cannon_F", 10],           
            ["I_APC_Wheeled_03_cannon_F", 10],
            
            //Tanks
            ["B_APC_Tracked_01_rcws_F", 50],
            ["B_APC_Tracked_01_CRV_F", 50],
            ["B_APC_Tracked_01_AA_F", 50],
            ["B_MBT_01_arty_F", 50],
            ["B_MBT_01_mlrs_F", 50],
            ["B_MBT_01_TUSK_F", 50],
            ["O_APC_Tracked_02_cannon_F", 50], 
            ["O_APC_Tracked_02_AA_F", 50],
            ["O_MBT_02_cannon_F", 50],
            ["O_MBT_02_arty_F", 50],
            ["O_APC_Wheeled_02_rcws_F", 50], 
            ["I_APC_tracked_03_cannon_F", 50],
            ["I_MBT_03_cannon_F", 50]
                      
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
    ["kart_01_base_f", 40],
    ["quadbike_01_base_f", 40],
    ["ugv_01_base_f", 100]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
    
];