/*

ExileZ Mod by [FPS]kuplion - Based on ExileZ 2.0 by Patrix87

*/

Private ["_weaponQuanity","_ammoQuanity","_attachmentQuanity","_headgearQuanity","_uniformQuanity","_backpackQuanity","_vestQuanity","_itemQuanity","_foodQuanity","_drinkQuanity","_medQuanity","_explosiveQuanity","_maxOfEach","_position","_weapons","_ammos","_attachments","_headgears","_uniforms","_backpacks","_vests","_items","_foods","_drinks","_meds","_explosives","_weapon","_ammo","_attachment","_headgear","_uniform","_backpack","_vest","_item","_food","_drink","_med","_explosive","_cargoBox","_lootBox","_antiflag"];

_weaponQuanity = 25;
_ammoQuanity = 15;
_attachmentQuanity = 10;
_headgearQuanity = 5;
_uniformQuanity = 10;
_backpackQuanity = 5;
_vestQuanity = 5;
_itemQuanity = 10;
_foodQuanity = 20;
_drinkQuanity = 20;
_medQuanity = 10;
_explosiveQuanity = 5;

_maxOfEach = 2;
_position = _this select 0;

_weapons = [
//Pistols
"hgun_ACPC2_F",
"hgun_P07_F",
"hgun_Pistol_heavy_01_F",
"hgun_Pistol_heavy_02_F",
"hgun_Pistol_Signal_F",
"hgun_Rook40_F",
"Exile_Weapon_Colt1911",
"Exile_Weapon_Makarov",
"Exile_Weapon_Taurus",
"Exile_Weapon_TaurusGold",
//Apex
"hgun_Pistol_01_F",
"hgun_P07_khk_F",
//SMG
"hgun_PDW2000_F",
"SMG_01_F",
"SMG_02_F",
"SMG_05_F",
//LMG
"arifle_MX_SW_Black_F",
"arifle_MX_SW_F",
"LMG_Mk200_F",
"LMG_Zafir_F",
"LMG_03_F",
"Exile_Weapon_RPK",
"Exile_Weapon_PK",
"Exile_Weapon_PKP",
"MMG_01_hex_F",
"MMG_01_tan_F",
"MMG_02_black_F",
"MMG_02_camo_F",
"MMG_02_sand_F",
//Assault Rifles
"arifle_Katiba_C_F",
"arifle_Katiba_F",
"arifle_Katiba_GL_F",
"arifle_Mk20_F",
"arifle_Mk20_GL_F",
"arifle_Mk20_GL_plain_F",
"arifle_Mk20_plain_F",
"arifle_Mk20C_F",
"arifle_Mk20C_plain_F",
"arifle_MX_Black_F",
"arifle_MX_F",
"arifle_MX_GL_Black_F",
"arifle_MX_GL_F",
"arifle_MXC_Black_F",
"arifle_MXC_F",
"arifle_SDAR_F",
"arifle_TRG20_F",
"arifle_TRG21_F",
"arifle_TRG21_GL_F",
"Exile_Weapon_AK107",
"Exile_Weapon_AK107_GL",
"Exile_Weapon_AK74",
"Exile_Weapon_AK74_GL",
"Exile_Weapon_AK47",
"Exile_Weapon_AKS_Gold",
//Apex
"arifle_AK12_F",
"arifle_AK12_GL_F",
"arifle_AKM_F",
"arifle_AKM_FL_F",
"arifle_AKS_F",
"arifle_ARX_blk_F",
"arifle_ARX_ghex_F",
"arifle_ARX_hex_F",
"arifle_CTAR_blk_F",
"arifle_CTAR_hex_F",
"arifle_CTAR_ghex_F",
"arifle_CTAR_GL_blk_F",
"arifle_CTARS_blk_F",
"arifle_CTARS_hex_F",
"arifle_CTARS_ghex_F",
"arifle_SPAR_01_blk_F",
"arifle_SPAR_01_khk_F",
"arifle_SPAR_01_snd_F",
"arifle_SPAR_01_GL_blk_F",
"arifle_SPAR_01_GL_khk_F",
"arifle_SPAR_01_GL_snd_F",
"arifle_SPAR_02_blk_F",
"arifle_SPAR_02_khk_F",
"arifle_SPAR_02_snd_F",			
"arifle_SPAR_03_blk_F",
"arifle_SPAR_03_khk_F",
"arifle_SPAR_03_snd_F",
"arifle_MX_khk_F",
"arifle_MX_GL_khk_F",
"arifle_MXC_khk_F",
"arifle_MXM_khk_F",
//Shotguns
"Exile_Weapon_M1014",
//Sniper Rifles
"arifle_MXM_Black_F",
"arifle_MXM_F",
"srifle_DMR_01_F",
"srifle_DMR_02_camo_F",
"srifle_DMR_02_F",
"srifle_DMR_02_sniper_F",
"srifle_DMR_03_F",
"srifle_DMR_03_khaki_F",
"srifle_DMR_03_multicam_F",
"srifle_DMR_03_tan_F",
"srifle_DMR_03_woodland_F",
"srifle_DMR_04_F",
"srifle_DMR_04_Tan_F",
"srifle_DMR_05_blk_F",
"srifle_DMR_05_hex_F",
"srifle_DMR_05_tan_f",
"srifle_DMR_06_camo_F",
"srifle_DMR_06_olive_F",
"srifle_EBR_F",
"srifle_GM6_camo_F",
"srifle_GM6_F",
"srifle_LRR_camo_F",
"srifle_LRR_F",
"Exile_Weapon_CZ550",
"Exile_Weapon_SVD",
"Exile_Weapon_SVDCamo",
"Exile_Weapon_VSSVintorez",
"Exile_Weapon_DMR",
"Exile_Weapon_LeeEnfield",
//Apex
"srifle_LRR_tna_F",
"srifle_GM6_ghex_F",
"srifle_DMR_07_blk_F",
"srifle_DMR_07_hex_F",
"srifle_DMR_07_ghex_F"
];

_ammos = [
"100Rnd_65x39_caseless_mag",
"100Rnd_65x39_caseless_mag_Tracer",
"10Rnd_127x54_Mag",
"10Rnd_338_Mag",
"10Rnd_762x54_Mag",
"10Rnd_93x64_DMR_05_Mag",
"11Rnd_45ACP_Mag",
"130Rnd_338_Mag",
"150Rnd_762x54_Box",
"150Rnd_762x54_Box_Tracer",
"150Rnd_93x64_Mag",
"16Rnd_9x21_Mag",
"200Rnd_65x39_cased_Box",
"200Rnd_65x39_cased_Box_Tracer",
"20Rnd_556x45_UW_mag",
"20Rnd_762x51_Mag",
"30Rnd_45ACP_Mag_SMG_01",
"30Rnd_45ACP_Mag_SMG_01_tracer_green",
"30Rnd_45ACP_Mag_SMG_01_Tracer_Red",
"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Green",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Yellow",
"30Rnd_65x39_caseless_green",
"30Rnd_65x39_caseless_green_mag_Tracer",
"30Rnd_65x39_caseless_mag",
"30Rnd_65x39_caseless_mag_Tracer",
"30Rnd_9x21_Mag",
"30Rnd_9x21_Yellow_Mag",
"30Rnd_9x21_Green_Mag",
"30Rnd_9x21_Red_Mag",
"5Rnd_127x108_APDS_Mag",
"5Rnd_127x108_Mag",
"6Rnd_45ACP_Cylinder",
"6Rnd_GreenSignal_F",
"6Rnd_RedSignal_F",
"7Rnd_408_Mag",
"9Rnd_45ACP_Mag",
"Exile_Magazine_30Rnd_762x39_AK",
"Exile_Magazine_30Rnd_545x39_AK_Green",
"Exile_Magazine_30Rnd_545x39_AK_Red",
"Exile_Magazine_30Rnd_545x39_AK_White",
"Exile_Magazine_30Rnd_545x39_AK_Yellow",
"Exile_Magazine_45Rnd_545x39_RPK_Green",
"Exile_Magazine_75Rnd_545x39_RPK_Green",
"Exile_Magazine_20Rnd_762x51_DMR",
"Exile_Magazine_20Rnd_762x51_DMR_Yellow",
"Exile_Magazine_20Rnd_762x51_DMR_Red",
"Exile_Magazine_20Rnd_762x51_DMR_Green",
"Exile_Magazine_10Rnd_303",
"Exile_Magazine_100Rnd_762x54_PK_Green",
"Exile_Magazine_7Rnd_45ACP",
"Exile_Magazine_8Rnd_9x18",
"Exile_Magazine_30Rnd_545x39_AK",
"Exile_Magazine_6Rnd_45ACP",
"Exile_Magazine_5Rnd_22LR",
"Exile_Magazine_10Rnd_762x54",
"Exile_Magazine_10Rnd_9x39",
"Exile_Magazine_20Rnd_9x39",
"Exile_Magazine_8Rnd_74Pellets",
"Exile_Magazine_8Rnd_74Slug",
//Apex
"30Rnd_9x21_Mag_SMG_02",
"30Rnd_9x21_Mag_SMG_02_Tracer_Red",
"30Rnd_9x21_Mag_SMG_02_Tracer_Yellow",
"30Rnd_9x21_Mag_SMG_02_Tracer_Green",
"30Rnd_580x42_Mag_F",
"30Rnd_580x42_Mag_Tracer_F",
"100Rnd_580x42_Mag_F",
"100Rnd_580x42_Mag_Tracer_F",
"20Rnd_650x39_Cased_Mag_F",
"10Rnd_50BW_Mag_F",
"150Rnd_556x45_Drum_Mag_F",
"150Rnd_556x45_Drum_Mag_Tracer_F",
"30Rnd_762x39_Mag_F",
"30Rnd_762x39_Mag_Green_F",
"30Rnd_762x39_Mag_Tracer_F",
"30Rnd_762x39_Mag_Tracer_Green_F",
"30Rnd_545x39_Mag_F",
"30Rnd_545x39_Mag_Green_F",
"30Rnd_545x39_Mag_Tracer_F",
"30Rnd_545x39_Mag_Tracer_Green_F",
"200Rnd_556x45_Box_F",
"200Rnd_556x45_Box_Red_F",
"200Rnd_556x45_Box_Tracer_F",
"200Rnd_556x45_Box_Tracer_Red_F",
"10Rnd_9x21_Mag",
"Exile_Magazine_5Rnd_127x108_Bullet_Cam_Mag",
"Exile_Magazine_10Rnd_93x64_DMR_05_Bullet_Cam_Mag",
"Exile_Magazine_7Rnd_408_Bullet_Cam_Mag",
"Exile_Magazine_10Rnd_338_Bullet_Cam_Mag"
];

_attachments = [
"bipod_01_F_blk",
"bipod_01_F_mtp",
"bipod_01_F_snd",
"bipod_02_F_blk",
"bipod_02_F_hex",
"bipod_02_F_tan",
"bipod_03_F_blk",
"bipod_03_F_oli",
"bipod_01_F_khk",
"muzzle_snds_338_black",
"muzzle_snds_338_green",
"muzzle_snds_338_sand",
"muzzle_snds_93mmg",
"muzzle_snds_93mmg_tan",
"muzzle_snds_acp",
"muzzle_snds_B",
"muzzle_snds_H",
"muzzle_snds_H_MG",
"muzzle_snds_H_SW",
"muzzle_snds_L",
"muzzle_snds_M",
"muzzle_snds_H_khk_F",
"muzzle_snds_H_snd_F",
"muzzle_snds_58_blk_F",
"muzzle_snds_m_khk_F",
"muzzle_snds_m_snd_F",
"muzzle_snds_B_khk_F",
"muzzle_snds_B_snd_F",
"muzzle_snds_58_wdm_F",
"muzzle_snds_65_TI_blk_F",
"muzzle_snds_65_TI_hex_F",
"muzzle_snds_65_TI_ghex_F",
"muzzle_snds_H_MG_blk_F",
"muzzle_snds_H_MG_khk_F",
"optic_Aco",
"optic_ACO_grn",
"optic_ACO_grn_smg",
"optic_Aco_smg",
"optic_AMS",
"optic_AMS_khk",
"optic_AMS_snd",
"optic_Arco",
"optic_DMS",
"optic_Hamr",
"optic_Holosight",
"optic_Holosight_smg",
"optic_KHS_blk",
"optic_KHS_hex",
"optic_KHS_old",
"optic_KHS_tan",
"optic_LRPS",
"optic_MRCO",
"optic_MRD",
"optic_Nightstalker",
"optic_NVS",
"optic_SOS",
"optic_tws",
"optic_tws_mg",
"optic_Yorris",
"optic_Arco_blk_F",
"optic_Arco_ghex_F",
"optic_DMS_ghex_F",
"optic_Hamr_khk_F",
"optic_ERCO_blk_F",
"optic_ERCO_khk_F",
"optic_ERCO_snd_F",
"optic_SOS_khk_F",
"optic_LRPS_tna_F",
"optic_LRPS_ghex_F",
"optic_Holosight_blk_F",
"optic_Holosight_khk_F",
"optic_Holosight_smg_blk_F"
];

_explosives = [
"HandGrenade",
"MiniGrenade",
"B_IR_Grenade",
"O_IR_Grenade",
"I_IR_Grenade",
"1Rnd_HE_Grenade_shell",
"3Rnd_HE_Grenade_shell",
"APERSBoundingMine_Range_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"DemoCharge_Remote_Mag",
"IEDLandBig_Remote_Mag",
"IEDLandSmall_Remote_Mag",
"IEDUrbanBig_Remote_Mag",
"IEDUrbanSmall_Remote_Mag",
"SatchelCharge_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag"
];

_headgears = [
"Exile_Headgear_SantaHat",
"Exile_Headgear_SafetyHelmet",
"H_Cap_blk",
"H_Cap_blk_Raven",
"H_Cap_blu",
"H_Cap_brn_SPECOPS",
"H_Cap_grn",
"H_Cap_headphones",
"H_Cap_khaki_specops_UK",
"H_Cap_oli",
"H_Cap_press",
"H_Cap_red",
"H_Cap_tan",
"H_Cap_tan_specops_US",
"H_Watchcap_blk",
"H_Watchcap_camo",
"H_Watchcap_khk",
"H_Watchcap_sgg",
"H_MilCap_blue",
"H_MilCap_dgtl",
"H_MilCap_mcamo",
"H_MilCap_ocamo",
"H_MilCap_oucamo",
"H_MilCap_rucamo",
"H_Bandanna_camo",
"H_Bandanna_cbr",
"H_Bandanna_gry",
"H_Bandanna_khk",
"H_Bandanna_khk_hs",
"H_Bandanna_mcamo",
"H_Bandanna_sgg",
"H_Bandanna_surfer",
"H_Booniehat_dgtl",
"H_Booniehat_dirty",
"H_Booniehat_grn",
"H_Booniehat_indp",
"H_Booniehat_khk",
"H_Booniehat_khk_hs",
"H_Booniehat_mcamo",
"H_Booniehat_tan",
"H_Hat_blue",
"H_Hat_brown",
"H_Hat_camo",
"H_Hat_checker",
"H_Hat_grey",
"H_Hat_tan",
"H_StrawHat",
"H_StrawHat_dark",
"H_Beret_02",
"H_Beret_blk",
"H_Beret_blk_POLICE",
"H_Beret_brn_SF",
"H_Beret_Colonel",
"H_Beret_grn",
"H_Beret_grn_SF",
"H_Beret_ocamo",
"H_Beret_red",
"H_Shemag_khk",
"H_Shemag_olive",
"H_Shemag_olive_hs",
"H_Shemag_tan",
"H_ShemagOpen_khk",
"H_ShemagOpen_tan",
"H_TurbanO_blk",
"H_HelmetB",
"H_HelmetB_black",
"H_HelmetB_camo",
"H_HelmetB_desert",
"H_HelmetB_grass",
"H_HelmetB_light",
"H_HelmetB_light_black",
"H_HelmetB_light_desert",
"H_HelmetB_light_grass",
"H_HelmetB_light_sand",
"H_HelmetB_light_snakeskin",
"H_HelmetB_paint",
"H_HelmetB_plain_blk",
"H_HelmetB_sand",
"H_HelmetB_snakeskin",
"H_HelmetCrew_B",
"H_HelmetCrew_I",
"H_HelmetCrew_O",
"H_HelmetIA",
"H_HelmetIA_camo",
"H_HelmetIA_net",
"H_HelmetLeaderO_ocamo",
"H_HelmetLeaderO_oucamo",
"H_HelmetO_ocamo",
"H_HelmetO_oucamo",
"H_HelmetSpecB",
"H_HelmetSpecB_blk",
"H_HelmetSpecB_paint1",
"H_HelmetSpecB_paint2",
"H_HelmetSpecO_blk",
"H_HelmetSpecO_ocamo",
"H_CrewHelmetHeli_B",
"H_CrewHelmetHeli_I",
"H_CrewHelmetHeli_O",
"H_HelmetCrew_I",
"H_HelmetCrew_B",
"H_HelmetCrew_O",
"H_PilotHelmetHeli_B",
"H_PilotHelmetHeli_I",
"H_PilotHelmetHeli_O",
//Apex
"H_Helmet_Skate",
"H_HelmetB_TI_tna_F",
"H_HelmetO_ViperSP_hex_F",
"H_HelmetO_ViperSP_ghex_F",
"H_HelmetB_tna_F",
"H_HelmetB_Enh_tna_F",
"H_HelmetB_Light_tna_F",
"H_HelmetSpecO_ghex_F",
"H_HelmetLeaderO_ghex_F",
"H_HelmetO_ghex_F",
"H_HelmetCrew_O_ghex_F",
"H_MilCap_tna_F",
"H_MilCap_ghex_F",
"H_Booniehat_tna_F",
"H_Beret_gen_F",
"H_MilCap_gen_F",
"H_Cap_oli_Syndikat_F",
"H_Cap_tan_Syndikat_F",
"H_Cap_blk_Syndikat_F",
"H_Cap_grn_Syndikat_F"
];

_uniforms = [
"U_C_Journalist",
"U_C_Poloshirt_blue",
"U_C_Poloshirt_burgundy",
"U_C_Poloshirt_salmon",
"U_C_Poloshirt_stripped",
"U_C_Poloshirt_tricolour",
"U_C_Poor_1",
"U_C_Poor_2",
"U_C_Poor_shorts_1",
"U_C_Scientist",
"U_OrestesBody",
"U_Rangemaster",
"U_NikosAgedBody",
"U_NikosBody",
"U_Competitor",
"U_B_CombatUniform_mcam",
"U_B_CombatUniform_mcam_tshirt",
"U_B_CombatUniform_mcam_vest",
"U_B_CombatUniform_mcam_worn",
"U_B_CTRG_1",
"U_B_CTRG_2",
"U_B_CTRG_3",
"U_I_CombatUniform",
"U_I_CombatUniform_shortsleeve",
"U_I_CombatUniform_tshirt",
"U_I_OfficerUniform",
"U_O_CombatUniform_ocamo",
"U_O_CombatUniform_oucamo",
"U_O_OfficerUniform_ocamo",
"U_B_SpecopsUniform_sgg",
"U_O_SpecopsUniform_blk",
"U_O_SpecopsUniform_ocamo",
"U_I_G_Story_Protagonist_F",
"Exile_Uniform_Woodland",
"U_C_HunterBody_grn",
"U_IG_Guerilla1_1",
"U_IG_Guerilla2_1",
"U_IG_Guerilla2_2",
"U_IG_Guerilla2_3",
"U_IG_Guerilla3_1",
"U_BG_Guerilla2_1",
"U_IG_Guerilla3_2",
"U_BG_Guerrilla_6_1",
"U_BG_Guerilla1_1",
"U_BG_Guerilla2_2",
"U_BG_Guerilla2_3",
"U_BG_Guerilla3_1",
"U_BG_leader",
"U_IG_leader",
"U_I_G_resistanceLeader_F",
"U_B_FullGhillie_ard",
"U_B_FullGhillie_lsh",
"U_B_FullGhillie_sard",
"U_B_GhillieSuit",
"U_I_FullGhillie_ard",
"U_I_FullGhillie_lsh",
"U_I_FullGhillie_sard",
"U_I_GhillieSuit",
"U_O_FullGhillie_ard",
"U_O_FullGhillie_lsh",
"U_O_FullGhillie_sard",
"U_O_GhillieSuit",
"U_I_Wetsuit",
"U_O_Wetsuit",
"U_B_Wetsuit",
"U_B_survival_uniform",
"U_B_HeliPilotCoveralls",
"U_I_HeliPilotCoveralls",
"U_B_PilotCoveralls",
"U_I_pilotCoveralls",
"U_O_PilotCoveralls",

//Apex
"U_B_T_Soldier_F",
"U_B_T_Soldier_AR_F",
"U_B_T_Soldier_SL_F",
"U_B_T_Sniper_F",
"U_B_T_FullGhillie_tna_F",
"U_B_CTRG_Soldier_F",
"U_B_CTRG_Soldier_2_F",
"U_B_CTRG_Soldier_3_F",
"U_B_GEN_Soldier_F",
"U_B_GEN_Commander_F",
"U_O_T_Soldier_F",
"U_O_T_Officer_F",
"U_O_T_Sniper_F",
"U_O_T_FullGhillie_tna_F",
"U_O_V_Soldier_Viper_F",
"U_O_V_Soldier_Viper_hex_F",
"U_I_C_Soldier_Para_1_F",
"U_I_C_Soldier_Para_2_F",
"U_I_C_Soldier_Para_3_F",
"U_I_C_Soldier_Para_4_F",
"U_I_C_Soldier_Para_5_F",
"U_I_C_Soldier_Bandit_1_F",
"U_I_C_Soldier_Bandit_2_F",
"U_I_C_Soldier_Bandit_3_F",
"U_I_C_Soldier_Bandit_4_F",
"U_I_C_Soldier_Bandit_5_F",
"U_I_C_Soldier_Camo_F",
"U_C_man_sport_1_F",
"U_C_man_sport_2_F",
"U_C_man_sport_3_F",
"U_C_Man_casual_1_F",
"U_C_Man_casual_2_F",
"U_C_Man_casual_3_F",
"U_C_Man_casual_4_F",
"U_C_Man_casual_5_F",
"U_C_Man_casual_6_F",
"U_B_CTRG_Soldier_urb_1_F",
"U_B_CTRG_Soldier_urb_2_F",
"U_B_CTRG_Soldier_urb_3_F"
];

_backpacks = [
"B_AssaultPack_blk",
"B_AssaultPack_cbr",
"B_AssaultPack_dgtl",
"B_AssaultPack_khk",
"B_AssaultPack_mcamo",
"B_AssaultPack_rgr",
"B_AssaultPack_sgg",
"B_Bergen_blk",
"B_Bergen_mcamo",
"B_Bergen_rgr",
"B_Bergen_sgg",
"B_Carryall_cbr",
"B_Carryall_khk",
"B_Carryall_mcamo",
"B_Carryall_ocamo",
"B_Carryall_oli",
"B_Carryall_oucamo",
"B_FieldPack_blk",
"B_FieldPack_cbr",
"B_FieldPack_ocamo",
"B_FieldPack_oucamo",
"B_HuntingBackpack",
"B_Kitbag_cbr",
"B_Kitbag_mcamo",
"B_Kitbag_sgg",
"B_OutdoorPack_blk",
"B_OutdoorPack_blu",
"B_OutdoorPack_tan",
"B_TacticalPack_blk",
"B_TacticalPack_mcamo",
"B_TacticalPack_ocamo",
"B_TacticalPack_oli",
"B_TacticalPack_rgr",
"B_Bergen_mcamo_F",
"B_Bergen_dgtl_F",
"B_Bergen_hex_F",
"B_Bergen_tna_F",
"B_AssaultPack_tna_F",
"B_Carryall_ghex_F",
"B_FieldPack_ghex_F",
"B_ViperHarness_blk_F",
"B_ViperHarness_ghex_F",
"B_ViperHarness_hex_F",
"B_ViperHarness_khk_F",
"B_ViperHarness_oli_F",
"B_ViperLightHarness_blk_F",
"B_ViperLightHarness_ghex_F",
"B_ViperLightHarness_hex_F",
"B_ViperLightHarness_khk_F",
"B_ViperLightHarness_oli_F"
];

_vests = [
"V_Press_F",
"V_Rangemaster_belt",
"V_TacVest_blk",
"V_TacVest_blk_POLICE",
"V_TacVest_brn",
"V_TacVest_camo",
"V_TacVest_khk",
"V_TacVest_oli",
"V_TacVestCamo_khk",
"V_TacVestIR_blk",
"V_I_G_resistanceLeader_F",
"V_BandollierB_blk",
"V_BandollierB_cbr",
"V_BandollierB_khk",
"V_BandollierB_oli",
"V_BandollierB_rgr",
"V_Chestrig_blk",
"V_Chestrig_khk",
"V_Chestrig_oli",
"V_Chestrig_rgr",
"V_HarnessO_brn",
"V_HarnessO_gry",
"V_HarnessOGL_brn",
"V_HarnessOGL_gry",
"V_HarnessOSpec_brn",
"V_HarnessOSpec_gry",
"V_PlateCarrier1_blk",
"V_PlateCarrier1_rgr",
"V_PlateCarrier2_rgr",
"V_PlateCarrier3_rgr",
"V_PlateCarrierGL_blk",
"V_PlateCarrierGL_mtp",
"V_PlateCarrierGL_rgr",
"V_PlateCarrierH_CTRG",
"V_PlateCarrierIA1_dgtl",
"V_PlateCarrierIA2_dgtl",
"V_PlateCarrierIAGL_dgtl",
"V_PlateCarrierIAGL_oli",
"V_PlateCarrierL_CTRG",
"V_PlateCarrierSpec_blk",
"V_PlateCarrierSpec_mtp",
"V_PlateCarrierSpec_rgr",
//Apex
"V_TacChestrig_grn_F",
"V_TacChestrig_oli_F",
"V_TacChestrig_cbr_F",
"V_PlateCarrier1_tna_F",
"V_PlateCarrier2_tna_F",
"V_PlateCarrierSpec_tna_F",
"V_PlateCarrierGL_tna_F",
"V_HarnessO_ghex_F",
"V_HarnessOGL_ghex_F",
"V_BandollierB_ghex_F",
"V_TacVest_gen_F",
"V_PlateCarrier1_rgr_noflag_F",
"V_PlateCarrier2_rgr_noflag_F"
];

_items = [
"DemoCharge_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag",
"IEDLandSmall_Remote_Mag",
"IEDUrbanSmall_Remote_Mag",
"HandGrenade",
"HandGrenade",
"HandGrenade",
"Exile_Item_SafeKit",
"Exile_Item_SafeKit",
"Exile_Item_SafeKit",
"NVGoggles",
"NVGoggles_INDEP",
"NVGoggles_OPFOR",
"Rangefinder",
"Laserdesignator",
"Laserdesignator_02",
"Laserdesignator_03",
"Exile_Item_Flag"
];

_drinks = [
"Exile_Item_PlasticBottleCoffee",
"Exile_Item_PowerDrink",
"Exile_Item_PlasticBottleFreshWater",
"Exile_Item_Beer",
"Exile_Item_EnergyDrink",
"Exile_Item_ChocolateMilk",
"Exile_Item_MountainDupe",
"Exile_Item_PlasticBottleEmpty"
];

_foods = [
"Exile_Item_EMRE",		
"Exile_Item_GloriousKnakworst",
"Exile_Item_Surstromming",
"Exile_Item_SausageGravy",
"Exile_Item_Catfood",
"Exile_Item_ChristmasTinner",
"Exile_Item_BBQSandwich",
"Exile_Item_MacasCheese",
"Exile_Item_Dogfood",
// Cooked Food
"Exile_Item_GloriousKnakworst_Cooked",
"Exile_Item_Surstromming_Cooked",
"Exile_Item_SausageGravy_Cooked",
"Exile_Item_ChristmasTinner_Cooked",
"Exile_Item_BBQSandwich_Cooked",
"Exile_Item_Catfood_Cooked",
"Exile_Item_DogFood_Cooked",
// Cooked Food
"Exile_Item_BeefParts",
"Exile_Item_Cheathas",
"Exile_Item_Noodles",
"Exile_Item_SeedAstics",
"Exile_Item_Raisins",
"Exile_Item_Moobar"
];

_meds = [
"Exile_Item_InstaDoc",
"Exile_Item_Bandage",
"Exile_Item_Vishpirin",
"Exile_Item_Heatpack",
"Exile_Item_Defibrillator"
];

_cargoBox = [
"B_CargoNet_01_ammo_F",
"O_CargoNet_01_ammo_F",
"I_CargoNet_01_ammo_F"	
];
	
//////////////////////////////////////////
/* DON'T EDIT BELOW ADVANCED USERS ONLY */
//////////////////////////////////////////

_lootBox = (selectRandom _cargoBox) createvehicle _position;
_antiflag = "Exile_Construction_Flag_Static" createvehicle _position;

clearMagazineCargoGlobal _lootBox;
clearWeaponCargoGlobal _lootBox;
clearItemCargoGlobal _lootBox;
_lootBox enableRopeAttach false;
_lootBox setVariable ["permaLoot",true];
_lootBox allowDamage false;

for "_i" from 1 to _weaponQuanity do {
	_weapon = selectRandom _weapons;
	_lootBox addItemCargoGlobal [_weapon, (ceil random _maxOfEach)];
};

for "_i" from 1 to _ammoQuanity do {
	_ammo = selectRandom _ammos;
	_lootBox addItemCargoGlobal [_ammo, (ceil random _maxOfEach)];
};

for "_i" from 1 to _attachmentQuanity do {
	_attachment = selectRandom _attachments;
	_lootBox addItemCargoGlobal [_attachment, (ceil random _maxOfEach)];
};

for "_i" from 1 to _headgearQuanity do {
	_headgear = selectRandom _headgears;
	_lootBox addItemCargoGlobal [_headgear, (ceil random _maxOfEach)];
};

for "_i" from 1 to _uniformQuanity do {
	_uniform = selectRandom _uniforms;
	_lootBox addItemCargoGlobal [_uniform, (ceil random _maxOfEach)];
};

for "_i" from 1 to _backpackQuanity do {
	_backpack = selectRandom _backpacks;
	_lootBox addItemCargoGlobal [_backpack, (ceil random _maxOfEach)];
};

for "_i" from 1 to _vestQuanity do {
	_vest = selectRandom _vests;
	_lootBox addItemCargoGlobal [_vest, (ceil random _maxOfEach)];
};

for "_i" from 1 to _itemQuanity do {
	_item = selectRandom _items;
	_lootBox addItemCargoGlobal [_item, (ceil random _maxOfEach)];
};

for "_i" from 1 to _foodQuanity do {
	_food = selectRandom _foods;
	_lootBox addItemCargoGlobal [_food, (ceil random _maxOfEach)];
};

for "_i" from 1 to _drinkQuanity do {
	_drink = selectRandom _drinks;
	_lootBox addItemCargoGlobal [_drink, (ceil random _maxOfEach)];
};

for "_i" from 1 to _medQuanity do {
	_med = selectRandom _meds;
	_lootBox addItemCargoGlobal [_med, (ceil random _maxOfEach)];
};

for "_i" from 1 to _explosiveQuanity do {
	_explosive = selectRandom _explosives;
	_lootBox addItemCargoGlobal [_explosive, (ceil random _maxOfEach)];
};